### ISSUE TITLE
naught deploy after server send('offline') AssertionError

### ISSUE THREAD

**Issue by KennyTw** [andrewrk/naught#68]
Hi
I follow previous document . when express server get error send 'offline' and do gracefulExit.
but after that , deploy a new update will cause a dying assert check

```
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: 1 === 0
    at /home/dev/code/node_modules/naught/lib/master.js:291:14
    at cbListener (/home/dev/code/node_modules/naught/node_modules/pend/index.js:49:5)
    at Array.forEach (native)
    at onCb (/home/dev/code/node_modules/naught/node_modules/pend/index.js:45:17)
    at Worker.onExit (/home/dev/code/node_modules/naught/lib/master.js:260:7)
    at Worker.emit (events.js:98:17)
    at ChildProcess.<anonymous> (cluster.js:345:10)
    at ChildProcess.g (events.js:180:16)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
```

what is the right procedure to send offline after error ? thank you

**Comment by forty** [comment]
much simpler code to trigger the bug:
```javascript
process.send('online')
setTimeout(function(){
    process.send('offline')
}, 1000);
```
then run:
naught start app.js
// wait 1 second for the app to then offline
naught deploy

this assert is indeed a big problem because it will crash naught each time we deploy just after an uncaught exception if the app did not have the time to finish to cleanly shutdown.
